use_frameworks!

platform :ios, '9.0'

target 'XXCommon_Example' do
  pod 'XXCommon', :path => '../'

  target 'XXCommon_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
